### ISSUE TITLE
Firedrake limiter masks Thetis limiter

### ISSUE THREAD

**Issue by tkarna** [thetisproject/thetis#64]
Thetis is not happy with the namespaces
```
In [1]: from thetis import *

In [2]: limiter.__name__
Out[2]: 'firedrake.slope_limiter.limiter'

In [3]: from thetis import limiter

In [4]: limiter.__name__
Out[4]: 'firedrake.slope_limiter.limiter'
```
How should I import `thetis.limiter` for this to work?

**Comment by wence-** [comment]
Think I fixed this.

**Comment by tkarna** [comment]
I still see the import issue with the 3D model, e.g. `test/bottomFriction/test_bottom_friction.py`.
This appears to work 8352bb4.

**Comment by wence-** [comment]
Looks right.  I think I don't understand how these `from . import limiter` picks up the firedrake limiter package when importing inside thetis, but `from thetis import limiter` gets the thetis limiter...

**Comment by tkarna** [comment]
Not clear to me either. I also don't know why this didn't show up in travis. It does show up here https://travis-ci.org/thetisproject/thetis/builds/147437571.
Anyway I'll push the fix and close this.

**Comment by tkarna** [comment]
Master is still failing. It seems I need to relax tolerance in `test/tracerEq/test_consistency.py`. Unrelated to the import bug, most likely due to some change in firedrake. Fixing the tolerance will most likely fix #65 as well.

**Comment by tkarna** [comment]
All green now. Closing.
